### ISSUE TITLE
Extend current integration tests to include apm-server and elasticsearch

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-js-base#10]
* [x] [Run apm-server and elastichsearch containers in travis](https://github.com/elastic/apm-agent-js-base/issues/19) 
* [x] Check the data stored in elasticsearch
* [x] Run agent e2e tests within apm-integration-tests

**Comment by alvarolobato** [comment]
@jahtalab will bring this proposal to the agents meeting.
