### ISSUE TITLE
Add Span.sync to xhr spans

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-js-base#100]
Defined in apm-server: https://github.com/elastic/apm-server/issues/1523

**Comment by jahtalab** [comment]
@vigneshshanmugam , but we need to add it to the payload we send to APM server.

**Comment by vigneshshanmugam** [comment]
@jahtalab Oops, I have a PR now https://github.com/elastic/apm-agent-js-core/pull/17
