### ISSUE TITLE
Revisit agent marks

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-js-base#12]
* Consider extending the agent marks.
* Remove `timeToComplete`
* Provide examples of agent marks, https://github.com/elastic/kibana/issues/18470#issuecomment-384610421

**Comment by formgeist** [comment]
@jahtalab Hey, have you had a chance to look at the examples for marks? Thanks 👍

**Comment by jahtalab** [comment]
@formgeist , Unfortunately not, I had to attend to some failing tests on travis. It is still failing but hopefully will be fixed soon then will get started on this!

**Comment by formgeist** [comment]
@jahtalab No worries 👍

**Comment by jahtalab** [comment]
@formgeist , I have updated [Marks example payload](https://github.com/elastic/apm-agent-js-core/wiki#marks) and the changes are released with v0.8.1. I haven't updated opbeans repo since we're in the middle of separating the frontend part of it. 

Let me know if you need more info.

**Comment by formgeist** [comment]
@jahtalab LGTM, I'll make some revisions to the designs on which we show the agent marks.

**Comment by alvarolobato** [comment]
Fixed here: https://github.com/elastic/apm-agent-js-core/commit/97ea33747e7bc81d2e26c9ffa6413fefb1f9cc83
