### ISSUE TITLE
Adding page load metrics to custom transactions

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-js-base#14]
* remove `TransactionService.sendPageLoadMetrics`
* use `TransactionService.startTransaction` with the type set to `page-load`

**Comment by vigneshshanmugam** [comment]
We currently don't use `TransactionService.sendPageLoadMetrics` anywhere other than for testing purposes. 

Closing the issue as its already done via setting type to `page-load`, Details here https://github.com/elastic/apm-agent-js-base/blob/e167d8de66029b1e560ded2d07987651ffedd61e/src/apm-base.js#L64-L67
