### ISSUE TITLE
Add service.runtime to the payload

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-js-base#151]
In order to be consistent with the data model we should provide a value for `service.runtime`, further more this value could be used for a visualisation in UI. Could use a constant string like `Browser` for the value.

**Comment by vigneshshanmugam** [comment]
serice.runtime is a object with name and version as keys as per the schema https://github.com/elastic/apm-server/blob/master/model/metadata/service.go#L79

**Comment by vigneshshanmugam** [comment]
We have decided to not add this to the metadata payload for now since it does not really give useful information other than displaying `browser` in runtime.
