### ISSUE TITLE
Travis: Create tunnel to saucelabs once per test

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-js-base#170]
Currently the tunnel is created once for unit tests and once e2e tests

**Comment by vigneshshanmugam** [comment]
Using single tunnel is possible only for sub accounts and goes against the best practices guide of running multiple tests in parallel. 

We are currently hit by our max concurrency of 5 sessions. So we cannot really make the tests parallel for both unit and e2e tests in rum.
