### ISSUE TITLE
Possible to exclude some spans?

### ISSUE THREAD

**Issue by yuxizhe** [elastic/apm-agent-js-base#181]
some request are very slow in China for examle Google-Analytics, which affect the accuracy of page load time. Is there a way to exclude them?
![image](https://user-images.githubusercontent.com/14990734/52768612-f5cb8a80-3068-11e9-89d8-f359187c46c9.png)

**Comment by vigneshshanmugam** [comment]
@yuxizhe yeah its possible using [addFilter API](https://www.elastic.co/guide/en/apm/agent/js-base/current/api.html#apm-add-filter), You would have to traverse the payload and find the span to exclude.  Something like below

```js
apm.addFilter(payload) {
  const { spans } = payload.transcations.spans;
  const filteredSpans = spans.filter(({name }) => {
    return name.indexOf('google-analytics') >= 0
  })
  payload.transcations.spans = filteredSpans;
  return payload  
}

```

**Comment by yuxizhe** [comment]
@vigneshshanmugam thanks for your inspiration！
