### ISSUE TITLE
Using CDN to load the agent causes : elasticApm is not defined

### ISSUE THREAD

**Issue by yuxizhe** [elastic/apm-agent-js-base#189]
I use https://cdn.jsdelivr.net/npm/elastic-apm-js-base@1.0.0/dist/bundles/elastic-apm-js-base.umd.js this CDN to load JavaScript agent. Because our ElasticSearch is v6.4 , we use elastic-apm-js-base@1.0.0. 

We can monitor datas in APM , but Sentry shows that there are errors,  elasticApm is not defined

![image](https://user-images.githubusercontent.com/14990734/52995979-1fb0f280-3457-11e9-86d0-d307b6c5bd14.png)

both Chrome and IE have this error

#### code: 
```html
<script src="https://cdn.jsdelivr.net/npm/elastic-apm-js-base@1.0.0/dist/bundles/elastic-apm-js-base.umd.js"></script>
<script>
  if(elasticApm){
  var apm = elasticApm.init({
    serviceName: '.....',
    serverUrl: '.....',
  })
</script>
```

**Comment by yuxizhe** [comment]
when I use window.elasticApm , problem was solved.

**Comment by vigneshshanmugam** [comment]
@yuxizhe This can only happen if the script itself failed to load which means `window.elasticApm` wont be present in the page, Can you check if thats the case? 

An easy way to test this case, is changing the version to some unknown number and you can see the browser throwing `Uncaught `ReferenceError: elasticApm is not defined`

**Comment by vigneshshanmugam** [comment]
> when I use window.elasticApm , problem was solved.

Yeah `window.elasticApm` does guarentee that the variable exists on the page, But you would still miss why the script failed to load in the first place.
