### ISSUE TITLE
Instrument fetch API

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-js-base#28]
- [x] Investigate [PerformanceResourceTiming](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming#Browser_compatibility)
- [x] Avoid duplicate spans when fetch is a polyfill
- [x] Remove domain from the url if on the same origin
- [x] Implement promise based instrumentation
- [x] Refactor XHR instrumentation
- [x] Add tests

**Comment by roncohen** [comment]
awesome @jahtalab !
