### ISSUE TITLE
Implement Intake V2 protocol

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-agent-js-base#43]
Related: https://github.com/elastic/apm-server/issues/1237
- [x] Implement ndjson.strigify
- [x] Add specific tests for ndjson
- [x] Provide required span count (#51)
- [x] Testing on apm-server v2 branch on travis
- [x] Review the proposal doc

**Comment by pgross41** [comment]
Is there a way to use an array instead of the ndjson format? Chrome's network tab does not know how to parse it so it's difficult to read. 

![image](https://user-images.githubusercontent.com/11710621/49674434-9aad6400-fa37-11e8-9639-c7a2a0d5b546.png)

**Comment by jahtalab** [comment]
Thanks for reaching out @pgross41 ,

Using ndjson allows our apm-server to read and process the payload more efficiently, it also allows agents to reduce their memory footprint by sending data as it becomes available.

Unfortunately, one of the trade-offs we had to make was readability of the payload. You can see elastic/apm-server#1237 for more information about our intake v2.

Cheers

**Comment by pgross41** [comment]
Thanks for the info @jahtalab
