### ISSUE TITLE
Allow sampling of transactions while monitoring all errors

### ISSUE THREAD

**Issue by danieljuhl** [elastic/apm-agent-js-base#49]
Right now sampling is suggested using `active: Math.random() < 0.1`. The way I read the docs, if I only enable for 10% of users, any errors on the 90% will never be reported to APM.

I would assume that errors is a rare but important thing, and I would like to have ALL errors reported to APM, while only sampling transactions/RUM.

Right now, I have simply set active to true, and the used `addFilter` to ignore all `payload.transactions`, as including these for all 100% of users is way too much data to process for our setup.

**Comment by jahtalab** [comment]
Thanks for reaching out @danieljuhl ,

I will make sure to update this issue with our progress on transaction sampling.

**Comment by jahtalab** [comment]
This is added through https://github.com/elastic/apm-agent-js-core/commit/8105e0c6f588e109e0521d31fe75070ab4b01ce0 and is planned to be released with version 2.0.0.
