### ISSUE TITLE
Provide a guide to setting initial page load transaction name

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-js-base#58]
Related: https://github.com/elastic/apm-agent-js-base/issues/56

**Comment by alvarolobato** [comment]
@bmorelli25  can you help with this? There are some docs already on this on the API side, but we need a good description on how to properly set the transaction name, which is very important because it leads to a better transaction grouping in the UI.

**Comment by alvarolobato** [comment]
Related to https://github.com/elastic/apm-agent-js-base/issues/93

**Comment by bmorelli25** [comment]
Sure, I can help! @jahtalab, I'll shoot you a calendar invite to jump on a call and discuss.
