### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by aqibnaushad** [elastic/apm-agent-js-base#64]
My APM is running on a server, when i am running web on local and pointing to my APM server i am getting error No 'Access-Control-Allow-Origin' header is present on the requested resource.
When i run my web as a microservice where my APM server is running then i am getting error "Failed sending transactions! Error: http://localhost:8200/v1/rum/transactions HTTP status: 0"
I am referring to https://www.elastic.co/guide/en/apm/agent/js-base/current/getting-started.html 
I have setup APM server as RPM.

Please help me in resolving the issue.

**Comment by jahtalab** [comment]
Hi @aqibnaushad , Sorry about the slow response.
There's a [configuration option ](https://www.elastic.co/guide/en/apm/server/current/configuration-rum.html#_literal_allow_origins_literal) that apm-server uses to add `Access-Control-Allow-Origin` header to the specified origins.

By default this configuration option is set to `allow_origins : ['*']` which should add `Access-Control-Allow-Origin` to all origins. 

Have you set this option on your apm-server configuration?

**Comment by jahtalab** [comment]
Closing the issue. Feel free to reopen if the issue persists.

**Comment by techsoldaten** [comment]
I am experiencing this exact issue. Allow origins is set as described. Here's a copy of the rum section from the YML file.

`
rum:
    # To enable real user monitoring (RUM) support set this to true.
    enabled: true

    # Rate limit per second and IP address for requests sent to the RUM endpoint.
    rate_limit: 10

    # Comma separated list of permitted origins for real user monitoring.
    # User-agents will send an origin header that will be validated against this list.
    # An origin is made of a protocol scheme, host and port, without the url path.
    # Allowed origins in this setting can have * to match anything (eg.: http://*.example.com)
    # If an item in the list is a single '*', everything will be allowed
    allow_origins : ['*']

    # Regexp to be matched against a stacktrace frame's `file_name` and `abs_path` attributes.
    # If the regexp matches, the stacktrace frame is considered to be a library frame.
    library_pattern: "node_modules|bower_components|~"

    # Regexp to be matched against a stacktrace frame's `file_name`.
    # If the regexp matches, the stacktrace frame is not used for calculating error groups.
    # The default pattern excludes stacktrace frames that have a filename starting with '/webpack'
    exclude_from_grouping: "^/webpack"

    # If a source map has previously been uploaded, source mapping is automatically applied
    # to all error and transaction documents sent to the RUM endpoint.
    source_mapping:

      # Source maps are always fetched from Elasticsearch, by default using the output.elasticsearch configuration.
      # A different instance must be configured when using any other output.
      # This setting only affects sourcemap reads - the output determines where sourcemaps are written.
      elasticsearch:
        # Array of hosts to connect to.
        # Scheme and port can be left out and will be set to the default (http and 9200)
        # In case you specify and additional path, the scheme is required: http://localhost:9200/path
        # IPv6 addresses should always be defined as: https://[2001:db8::1]:9200
        hosts: ["localhost:9200"]

        # Optional protocol and basic auth credentials.
        #protocol: "https"
        #username: "elastic"
        #password: "changeme"

      # The `cache.expiration` determines how long a source map should be cached before fetching it again from Elasticsearch.
      # Note that values configured without a time unit will be interpreted as seconds.
      #cache:
        #expiration: 5m

      # Source maps are stored in a seperate index.
      # If the default index pattern for source maps at 'outputs.elasticsearch.indices'
      # is changed, a matching index pattern needs to be specified here.
      index_pattern: "apm-*-sourcemap*"`

**Comment by jahtalab** [comment]
Thanks for reporting the issue @techsoldaten ,

Would you please post the OPTIONS request made to the apm-server in HAR format?
(There's menu option called "copy as HAR" in the networks panel)

**Comment by jahtalab** [comment]
Closing the issue as there was no response, feel free to reopen.
