### ISSUE TITLE
Implement URL parser in the agent

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-js-base#67]
Currently we use https://www.npmjs.com/package/url-parse to parse url, however this project provides more functionality than we need and increases the final package size.
We should implement our own URL parser with only the functions that we need

**Comment by vigneshshanmugam** [comment]
Since we use the bare minimal feature, We can go with the easy option of using the method described [here](https://github.com/arv/DOM-URL-Polyfill/blob/master/src/url.js) to avoid the large bundle size. 

A stripped down version of that package would solve our purpose.
