### ISSUE TITLE
Can I use it with my php app?

### ISSUE THREAD

**Issue by dmpopoff** [elastic/apm-agent-js-base#69]
For example: I copy some js file from this repo to my web server, make configuration changes in it (point link to my elastic APM server), client browser go to my app link and with all site content download js too. Js work on client side by sending browser metrics and http errors and so on to APM server. Is it possible? Which js should I deploy to my web?

**Comment by jahtalab** [comment]
Thanks for reaching out @dmpopoff ,

In short you need to add the following snippet to the top level html template:

```html
<script src="elastic-apm-js-base/dist/bundles/elastic-apm-js-base.umd.min.js"></script>
<script>
  elasticApm.init({
    serviceName: '<service-name>',
    serverUrl: 'http://localhost:8200',
  })
elasticApm.setInitialPageLoadName('<page-name>');
</script>
```

See our [documentation](https://www.elastic.co/guide/en/apm/agent/js-base/current/index.html) for more information on how to configure the agent.

**Comment by jahtalab** [comment]
I'm closing this, feel free to reopen if needed!
