### ISSUE TITLE
Support for custom marks

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-js-base#9]
* Need to provide an API to record custom marks on the current transaction. 
* Consider capturing marks added by using `performance.mark`.
* Add docs
* Add example marks to opbeans

**Comment by alvarolobato** [comment]
Fixed in https://github.com/elastic/apm-agent-js-base/commit/4d2b71b2a82e83c497976f4ea25bf22d7810f10f and https://github.com/elastic/apm-agent-js-core/commit/3de6b1048b810f2d2a76bd68a18c25da3eb3a477
